#include "capture_slots.h"

#include <algorithm>
#include <cstdio>
#include <new>

#include "d3d12_presenter.h"  // IID_ReShadeUnwrappedObject
#include "depth_blit_cs.h"    // kDepthBlitCs, generated by fxc at build time
#include "log.h"

using Microsoft::WRL::ComPtr;

namespace acdb {
namespace {

// Source-view cache (spec 6.5): CSP's depth is usually one stable texture, so
// a few entries are plenty. An entry holds its source alive (the SRV does
// anyway), so it is dropped once unused for kStaleAfterCopies copies.
constexpr size_t kMaxCachedViews = 4;
constexpr uint64_t kStaleAfterCopies = 4;
constexpr UINT kBlitGroup = 8;  // [numthreads(8, 8, 1)] in shaders/depth_blit.hlsl
constexpr UINT kKeepUavCounter = static_cast<UINT>(-1);

std::string HrText(const char* what, HRESULT hr) {
    char buf[200];
    std::snprintf(buf, sizeof(buf), "%s failed: 0x%08lX", what, static_cast<unsigned long>(hr));
    return buf;
}

void SetError(std::string* error, const std::string& text) {
    if (!error) return;
    try {
        *error = text;
    } catch (...) {
    }
}

// The Texture2D behind a resource, with its desc; false for other resources.
bool AsTexture2D(ID3D11Resource* resource, ComPtr<ID3D11Texture2D>* tex, D3D11_TEXTURE2D_DESC* desc) {
    if (!resource) return false;
    D3D11_RESOURCE_DIMENSION dim = D3D11_RESOURCE_DIMENSION_UNKNOWN;
    resource->GetType(&dim);
    if (dim != D3D11_RESOURCE_DIMENSION_TEXTURE2D) return false;
    if (FAILED(resource->QueryInterface(IID_PPV_ARGS(tex->ReleaseAndGetAddressOf())))) return false;
    (*tex)->GetDesc(desc);
    return true;
}

// Matches compares exactly these fields (spec 6.4 "When recreated").
bool SameSourceDesc(const D3D11_TEXTURE2D_DESC& a, const D3D11_TEXTURE2D_DESC& b) {
    return a.Format == b.Format && a.Width == b.Width && a.Height == b.Height &&
           a.SampleDesc.Count == b.SampleDesc.Count && a.SampleDesc.Quality == b.SampleDesc.Quality;
}

// The COM identity (IUnknown) of the native device: a ReShade proxy device
// answers IID_ReShadeUnwrappedObject with the device it wraps; any other
// device is its own native device.
ComPtr<IUnknown> NativeIdentity(ID3D11Device* device) {
    ComPtr<IUnknown> unwrapped;
    IUnknown* native = device;
    if (SUCCEEDED(device->QueryInterface(IID_ReShadeUnwrappedObject,
                                         reinterpret_cast<void**>(unwrapped.GetAddressOf()))) &&
        unwrapped)
        native = unwrapped.Get();
    ComPtr<IUnknown> identity;
    native->QueryInterface(IID_PPV_ARGS(&identity));
    return identity;
}

bool OwnedBy(ID3D11DeviceChild* child, IUnknown* nativeIdentity) {
    ComPtr<ID3D11Device> owner;
    child->GetDevice(&owner);
    return owner && NativeIdentity(owner.Get()).Get() == nativeIdentity;
}

const char* FormatName(DXGI_FORMAT f) {
    switch (f) {
        case DXGI_FORMAT_R32_TYPELESS: return "R32_TYPELESS";
        case DXGI_FORMAT_R32_FLOAT: return "R32_FLOAT";
        case DXGI_FORMAT_D32_FLOAT: return "D32_FLOAT";
        case DXGI_FORMAT_R24G8_TYPELESS: return "R24G8_TYPELESS";
        case DXGI_FORMAT_D24_UNORM_S8_UINT: return "D24_UNORM_S8_UINT";
        case DXGI_FORMAT_R16_TYPELESS: return "R16_TYPELESS";
        case DXGI_FORMAT_R16_UNORM: return "R16_UNORM";
        case DXGI_FORMAT_D16_UNORM: return "D16_UNORM";
        case DXGI_FORMAT_R32G8X24_TYPELESS: return "R32G8X24_TYPELESS";
        case DXGI_FORMAT_D32_FLOAT_S8X24_UINT: return "D32_FLOAT_S8X24_UINT";
        case DXGI_FORMAT_R16G16_FLOAT: return "R16G16_FLOAT";
        case DXGI_FORMAT_R16G16_TYPELESS: return "R16G16_TYPELESS";
        case DXGI_FORMAT_R32G32_FLOAT: return "R32G32_FLOAT";
        case DXGI_FORMAT_R32G32_TYPELESS: return "R32G32_TYPELESS";
        default: return nullptr;
    }
}

std::string FormatText(DXGI_FORMAT f) {
    if (const char* name = FormatName(f)) return name;
    return "format " + std::to_string(static_cast<int>(f));
}

std::string DescText(const D3D11_TEXTURE2D_DESC& d) {
    char buf[160];
    std::snprintf(buf, sizeof(buf), "%ux%u %s x%u", d.Width, d.Height, FormatText(d.Format).c_str(),
                  d.SampleDesc.Count);
    return buf;
}

// A texture created on D3D11 with MISC_SHARED | MISC_SHARED_NTHANDLE, shared
// with CreateSharedHandle and opened on D3D12, as the presenter's shared back
// buffer (spec 6.4).
bool CreateShared(ID3D11Device* device11, ID3D12Device* device12, const D3D11_TEXTURE2D_DESC& desc, const char* what,
                  ComPtr<ID3D11Texture2D>* tex11, ComPtr<ID3D12Resource>* tex12, std::string* err) {
    std::string prefix = std::string("capture slot ") + what + " ";
    ComPtr<ID3D11Texture2D> tex;
    HRESULT hr = device11->CreateTexture2D(&desc, nullptr, &tex);
    if (FAILED(hr)) {
        *err = HrText((prefix + "CreateTexture2D(" + DescText(desc) + ")").c_str(), hr);
        return false;
    }
    ComPtr<IDXGIResource1> resource;
    HANDLE handle = nullptr;
    hr = tex.As(&resource);
    if (SUCCEEDED(hr))
        hr = resource->CreateSharedHandle(nullptr, DXGI_SHARED_RESOURCE_READ | DXGI_SHARED_RESOURCE_WRITE, nullptr,
                                          &handle);
    if (FAILED(hr)) {
        *err = HrText((prefix + "CreateSharedHandle").c_str(), hr);
        return false;
    }
    ComPtr<ID3D12Resource> opened;
    hr = device12->OpenSharedHandle(handle, IID_PPV_ARGS(&opened));
    CloseHandle(handle);
    if (FAILED(hr)) {
        *err = HrText((prefix + "OpenSharedHandle").c_str(), hr);
        return false;
    }
    *tex11 = tex;
    *tex12 = opened;
    return true;
}

// The compute state the blit changes: the shader with its class instances,
// SRV slot 0 and UAV slot 0 (spec 6.5). Restored in reverse order; the UAV is
// re-bound with an initial count of -1, which keeps its hidden counter.
class ComputeStateGuard {
public:
    explicit ComputeStateGuard(ID3D11DeviceContext* ctx) : ctx_(ctx) {
        instance_count_ = D3D11_SHADER_MAX_INTERFACES;
        ctx_->CSGetShader(&shader_, instances_, &instance_count_);
        ctx_->CSGetShaderResources(0, 1, &srv_);
        ctx_->CSGetUnorderedAccessViews(0, 1, &uav_);
    }
    ~ComputeStateGuard() {
        ID3D11ShaderResourceView* srv = srv_.Get();
        ctx_->CSSetShaderResources(0, 1, &srv);
        ID3D11UnorderedAccessView* uav = uav_.Get();
        ctx_->CSSetUnorderedAccessViews(0, 1, &uav, &kKeepUavCounter);
        ctx_->CSSetShader(shader_.Get(), instance_count_ ? instances_ : nullptr, instance_count_);
        for (UINT i = 0; i < instance_count_; ++i)
            if (instances_[i]) instances_[i]->Release();
    }
    ComputeStateGuard(const ComputeStateGuard&) = delete;
    ComputeStateGuard& operator=(const ComputeStateGuard&) = delete;

private:
    ID3D11DeviceContext* ctx_;
    ComPtr<ID3D11ComputeShader> shader_;
    ID3D11ClassInstance* instances_[D3D11_SHADER_MAX_INTERFACES] = {};
    UINT instance_count_ = 0;
    ComPtr<ID3D11ShaderResourceView> srv_;
    ComPtr<ID3D11UnorderedAccessView> uav_;
};

// Unbinds the output-merger depth-stencil view for the blit when it is a view
// of the depth source (D3D11 forces an SRV of a resource bound for output to
// NULL) and re-binds it, with the same render targets, on destruction. The
// output-merger UAVs are kept (D3D11_KEEP_UNORDERED_ACCESS_VIEWS).
class DepthStencilUnbind {
public:
    DepthStencilUnbind(ID3D11DeviceContext* ctx, ID3D11Resource* depth) : ctx_(ctx) {
        ctx_->OMGetRenderTargets(D3D11_SIMULTANEOUS_RENDER_TARGET_COUNT, rtvs_, &dsv_);
        for (UINT i = 0; i < D3D11_SIMULTANEOUS_RENDER_TARGET_COUNT; ++i)
            if (rtvs_[i]) rtv_count_ = i + 1;
        if (!dsv_) return;
        ComPtr<ID3D11Resource> bound;
        dsv_->GetResource(&bound);
        if (bound.Get() != depth) return;
        ctx_->OMSetRenderTargetsAndUnorderedAccessViews(rtv_count_, rtvs_, nullptr, 0,
                                                        D3D11_KEEP_UNORDERED_ACCESS_VIEWS, nullptr, nullptr);
        active_ = true;
    }
    ~DepthStencilUnbind() {
        if (active_)
            ctx_->OMSetRenderTargetsAndUnorderedAccessViews(rtv_count_, rtvs_, dsv_.Get(), 0,
                                                            D3D11_KEEP_UNORDERED_ACCESS_VIEWS, nullptr, nullptr);
        for (auto* rtv : rtvs_)
            if (rtv) rtv->Release();
    }
    DepthStencilUnbind(const DepthStencilUnbind&) = delete;
    DepthStencilUnbind& operator=(const DepthStencilUnbind&) = delete;
    bool Active() const { return active_; }

private:
    ID3D11DeviceContext* ctx_;
    ID3D11RenderTargetView* rtvs_[D3D11_SIMULTANEOUS_RENDER_TARGET_COUNT] = {};
    UINT rtv_count_ = 0;
    ComPtr<ID3D11DepthStencilView> dsv_;
    bool active_ = false;
};

bool BoundSrv0Is(ID3D11DeviceContext* ctx, ID3D11ShaderResourceView* expected) {
    ComPtr<ID3D11ShaderResourceView> bound;
    ctx->CSGetShaderResources(0, 1, &bound);
    return bound.Get() == expected;
}

}  // namespace

DepthFormatInfo DepthSourceFormat(DXGI_FORMAT source) {
    switch (source) {
        case DXGI_FORMAT_R32_TYPELESS:
        case DXGI_FORMAT_R32_FLOAT:
        case DXGI_FORMAT_D32_FLOAT:
            return {DXGI_FORMAT_R32_FLOAT, DXGI_FORMAT_R32_TYPELESS};
        case DXGI_FORMAT_R24G8_TYPELESS:
        case DXGI_FORMAT_D24_UNORM_S8_UINT:
            return {DXGI_FORMAT_R24_UNORM_X8_TYPELESS, DXGI_FORMAT_R24G8_TYPELESS};
        case DXGI_FORMAT_R16_TYPELESS:
        case DXGI_FORMAT_R16_UNORM:
        case DXGI_FORMAT_D16_UNORM:
            return {DXGI_FORMAT_R16_UNORM, DXGI_FORMAT_R16_TYPELESS};
        case DXGI_FORMAT_R32G8X24_TYPELESS:
        case DXGI_FORMAT_D32_FLOAT_S8X24_UINT:
            return {DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS, DXGI_FORMAT_R32G8X24_TYPELESS};
        default:
            return {};
    }
}

DXGI_FORMAT TypedMvecFormat(DXGI_FORMAT source) {
    switch (source) {
        case DXGI_FORMAT_R16G16_TYPELESS: return DXGI_FORMAT_R16G16_FLOAT;
        case DXGI_FORMAT_R32G32_TYPELESS: return DXGI_FORMAT_R32G32_FLOAT;
        case DXGI_FORMAT_R16G16B16A16_TYPELESS: return DXGI_FORMAT_R16G16B16A16_FLOAT;
        case DXGI_FORMAT_R32G32B32A32_TYPELESS: return DXGI_FORMAT_R32G32B32A32_FLOAT;
        // No typed guess for the other typeless families.
        case DXGI_FORMAT_UNKNOWN:
        case DXGI_FORMAT_R32G32B32_TYPELESS:
        case DXGI_FORMAT_R32G8X24_TYPELESS:
        case DXGI_FORMAT_R10G10B10A2_TYPELESS:
        case DXGI_FORMAT_R8G8B8A8_TYPELESS:
        case DXGI_FORMAT_R32_TYPELESS:
        case DXGI_FORMAT_R24G8_TYPELESS:
        case DXGI_FORMAT_R8G8_TYPELESS:
        case DXGI_FORMAT_R16_TYPELESS:
        case DXGI_FORMAT_R8_TYPELESS:
        case DXGI_FORMAT_B8G8R8A8_TYPELESS:
        case DXGI_FORMAT_B8G8R8X8_TYPELESS:
        case DXGI_FORMAT_BC1_TYPELESS:
        case DXGI_FORMAT_BC2_TYPELESS:
        case DXGI_FORMAT_BC3_TYPELESS:
        case DXGI_FORMAT_BC4_TYPELESS:
        case DXGI_FORMAT_BC5_TYPELESS:
        case DXGI_FORMAT_BC6H_TYPELESS:
        case DXGI_FORMAT_BC7_TYPELESS:
        // Depth formats are no motion vectors.
        case DXGI_FORMAT_D32_FLOAT_S8X24_UINT:
        case DXGI_FORMAT_D32_FLOAT:
        case DXGI_FORMAT_D24_UNORM_S8_UINT:
        case DXGI_FORMAT_D16_UNORM:
            return DXGI_FORMAT_UNKNOWN;
        default:
            return source;
    }
}

struct CaptureSlots::Slot {
    ComPtr<ID3D11Texture2D> depth11;
    ComPtr<ID3D11UnorderedAccessView> depth_uav;
    ComPtr<ID3D12Resource> depth12;
    ComPtr<ID3D11Texture2D> mvec11;
    ComPtr<ID3D12Resource> mvec12;
    DXGI_FORMAT mvec_format = DXGI_FORMAT_UNKNOWN;
    // The sources' descs at the last Recreate (Matches compares with these).
    D3D11_TEXTURE2D_DESC depth_source{};
    D3D11_TEXTURE2D_DESC mvec_source{};
};

// The typed SRV for one depth source. A source without BIND_SHADER_RESOURCE
// is first copied into `copy`, a texture of its typeless family that has it.
struct CaptureSlots::SourceView {
    ComPtr<ID3D11Resource> source;  // held, so the pointer key cannot be reused
    ComPtr<ID3D11Texture2D> copy;
    ComPtr<ID3D11ShaderResourceView> srv;
    uint64_t last_use = 0;
};

CaptureSlots::CaptureSlots() = default;
CaptureSlots::~CaptureSlots() = default;

std::unique_ptr<CaptureSlots> CaptureSlots::Create(ID3D11Device* device11, ID3D12Device* device12,
                                                   std::string* error) {
    try {
        if (!device11 || !device12) {
            SetError(error, "CaptureSlots: null device");
            return nullptr;
        }
        std::unique_ptr<CaptureSlots> p(new (std::nothrow) CaptureSlots());
        if (!p) {
            SetError(error, "CaptureSlots: out of memory");
            return nullptr;
        }
        p->slots_.reset(new (std::nothrow) Slot[kSlots]);
        if (!p->slots_) {
            SetError(error, "CaptureSlots: out of memory");
            return nullptr;
        }
        // Cross-API sharing needs both devices on one adapter.
        ComPtr<IDXGIDevice> dxgi;
        ComPtr<IDXGIAdapter> adapter;
        DXGI_ADAPTER_DESC ad{};
        HRESULT hr = device11->QueryInterface(IID_PPV_ARGS(&dxgi));
        if (SUCCEEDED(hr)) hr = dxgi->GetAdapter(&adapter);
        if (SUCCEEDED(hr)) hr = adapter->GetDesc(&ad);
        if (FAILED(hr)) {
            SetError(error, HrText("CaptureSlots: adapter of the D3D11 device", hr));
            return nullptr;
        }
        const LUID luid12 = device12->GetAdapterLuid();
        if (luid12.LowPart != ad.AdapterLuid.LowPart || luid12.HighPart != ad.AdapterLuid.HighPart) {
            SetError(error, "CaptureSlots: the D3D11 and D3D12 devices are on different adapters");
            return nullptr;
        }
        hr = device11->CreateComputeShader(kDepthBlitCs, sizeof(kDepthBlitCs), nullptr, &p->blit_);
        if (FAILED(hr)) {
            SetError(error, HrText("CaptureSlots: CreateComputeShader(depth blit)", hr));
            return nullptr;
        }
        p->device11_ = device11;
        p->device12_ = device12;
        return p;
    } catch (...) {
        SetError(error, "CaptureSlots: exception during creation");
        return nullptr;
    }
}

bool CaptureSlots::Valid(uint32_t slot) const { return slots_ && slot < kSlots; }

bool CaptureSlots::HasTextures(uint32_t slot) const { return Valid(slot) && slots_[slot].depth11; }

bool CaptureSlots::Matches(uint32_t slot, ID3D11Resource* depth, ID3D11Resource* mvec) const {
    if (!HasTextures(slot)) return false;
    ComPtr<ID3D11Texture2D> tex;
    D3D11_TEXTURE2D_DESC desc{};
    if (!AsTexture2D(depth, &tex, &desc) || !SameSourceDesc(desc, slots_[slot].depth_source)) return false;
    if (!AsTexture2D(mvec, &tex, &desc) || !SameSourceDesc(desc, slots_[slot].mvec_source)) return false;
    return true;
}

bool CaptureSlots::Recreate(uint32_t slot, ID3D11Resource* depth, ID3D11Resource* mvec, std::string* error) {
    if (!Valid(slot)) {
        SetError(error, "CaptureSlots: slot index out of range");
        return false;
    }
    std::string err;
    try {
        // Release first: a refused source leaves the slot empty.
        slots_[slot] = Slot();
        // Views hold their sources; after a resize the old ones must go.
        views_.clear();

        ComPtr<ID3D11Texture2D> depthTex, mvecTex;
        D3D11_TEXTURE2D_DESC dd{}, md{};
        const ComPtr<IUnknown> native = NativeIdentity(device11_.Get());
        if (!AsTexture2D(depth, &depthTex, &dd)) {
            err = "depth source is not a Texture2D";
        } else if (!AsTexture2D(mvec, &mvecTex, &md)) {
            err = "motion-vector source is not a Texture2D";
        } else if (dd.SampleDesc.Count != 1 || md.SampleDesc.Count != 1) {
            err = "MSAA sources are not supported (depth " + DescText(dd) + ", motion vectors " + DescText(md) + ")";
        } else if (dd.ArraySize != 1 || md.ArraySize != 1) {
            err = "texture arrays are not supported";
        } else if (DepthSourceFormat(dd.Format).srv == DXGI_FORMAT_UNKNOWN) {
            err = "unsupported depth format " + FormatText(dd.Format);
        } else if (TypedMvecFormat(md.Format) == DXGI_FORMAT_UNKNOWN) {
            err = "unsupported motion-vector format " + FormatText(md.Format);
        } else if (!OwnedBy(depthTex.Get(), native.Get()) || !OwnedBy(mvecTex.Get(), native.Get())) {
            err = "a source belongs to another D3D11 device";
        }

        Slot s;
        if (err.empty()) {
            // Each texture takes its size from its own source (spec 6.4).
            D3D11_TEXTURE2D_DESC td{};
            td.Width = dd.Width;
            td.Height = dd.Height;
            td.MipLevels = 1;
            td.ArraySize = 1;
            td.Format = DXGI_FORMAT_R32_FLOAT;
            td.SampleDesc.Count = 1;
            td.Usage = D3D11_USAGE_DEFAULT;
            td.BindFlags = D3D11_BIND_UNORDERED_ACCESS | D3D11_BIND_SHADER_RESOURCE;
            td.MiscFlags = D3D11_RESOURCE_MISC_SHARED | D3D11_RESOURCE_MISC_SHARED_NTHANDLE;
            if (CreateShared(device11_.Get(), device12_.Get(), td, "depth", &s.depth11, &s.depth12, &err)) {
                const HRESULT hr = device11_->CreateUnorderedAccessView(s.depth11.Get(), nullptr, &s.depth_uav);
                if (FAILED(hr)) err = HrText("capture slot depth CreateUnorderedAccessView", hr);
            }
        }
        if (err.empty()) {
            D3D11_TEXTURE2D_DESC td{};
            td.Width = md.Width;
            td.Height = md.Height;
            td.MipLevels = 1;
            td.ArraySize = 1;
            td.Format = TypedMvecFormat(md.Format);
            td.SampleDesc.Count = 1;
            td.Usage = D3D11_USAGE_DEFAULT;
            td.BindFlags = D3D11_BIND_SHADER_RESOURCE;
            td.MiscFlags = D3D11_RESOURCE_MISC_SHARED | D3D11_RESOURCE_MISC_SHARED_NTHANDLE;
            if (CreateShared(device11_.Get(), device12_.Get(), td, "motion vectors", &s.mvec11, &s.mvec12, &err))
                s.mvec_format = td.Format;
        }
        if (!err.empty()) {
            SetError(error, "CaptureSlots: slot " + std::to_string(slot) + ": " + err);
            return false;
        }
        s.depth_source = dd;
        s.mvec_source = md;
        slots_[slot] = std::move(s);
        LOGI("capture slot %u: depth %s -> %ux%u R32_FLOAT, motion vectors %s -> %ux%u %s", slot,
             DescText(dd).c_str(), dd.Width, dd.Height, DescText(md).c_str(), md.Width, md.Height,
             FormatText(slots_[slot].mvec_format).c_str());
        return true;
    } catch (...) {
        slots_[slot] = Slot();
        SetError(error, "CaptureSlots: exception in Recreate");
        return false;
    }
}

CaptureSlots::SourceView* CaptureSlots::ViewFor(ID3D11Texture2D* depth, std::string* error) {
    // Drop entries unused for a while, then look the source up.
    views_.erase(std::remove_if(views_.begin(), views_.end(),
                                [&](const SourceView& v) { return copies_ - v.last_use > kStaleAfterCopies; }),
                 views_.end());
    for (SourceView& v : views_) {
        if (v.source.Get() == depth) {
            v.last_use = copies_;
            return &v;
        }
    }
    if (views_.size() >= kMaxCachedViews) {
        views_.erase(std::min_element(views_.begin(), views_.end(), [](const SourceView& a, const SourceView& b) {
            return a.last_use < b.last_use;
        }));
    }

    D3D11_TEXTURE2D_DESC desc{};
    depth->GetDesc(&desc);
    const DepthFormatInfo info = DepthSourceFormat(desc.Format);
    SourceView v;
    v.source = depth;
    v.last_use = copies_;
    ID3D11Resource* viewed = depth;
    if (!(desc.BindFlags & D3D11_BIND_SHADER_RESOURCE)) {
        // Typed depth formats cannot have an SRV; read a copy of the family.
        D3D11_TEXTURE2D_DESC cd{};
        cd.Width = desc.Width;
        cd.Height = desc.Height;
        cd.MipLevels = 1;
        cd.ArraySize = 1;
        cd.Format = info.family;
        cd.SampleDesc.Count = 1;
        cd.Usage = D3D11_USAGE_DEFAULT;
        cd.BindFlags = D3D11_BIND_SHADER_RESOURCE;
        const HRESULT hr = device11_->CreateTexture2D(&cd, nullptr, &v.copy);
        if (FAILED(hr)) {
            *error = HrText(("depth copy CreateTexture2D(" + DescText(cd) + ")").c_str(), hr);
            return nullptr;
        }
        viewed = v.copy.Get();
    }
    D3D11_SHADER_RESOURCE_VIEW_DESC sd{};
    sd.Format = info.srv;
    sd.ViewDimension = D3D11_SRV_DIMENSION_TEXTURE2D;
    sd.Texture2D.MostDetailedMip = 0;
    sd.Texture2D.MipLevels = 1;
    const HRESULT hr = device11_->CreateShaderResourceView(viewed, &sd, &v.srv);
    if (FAILED(hr)) {
        *error = HrText(("depth CreateShaderResourceView(" + FormatText(info.srv) + ")").c_str(), hr);
        return nullptr;
    }
    views_.push_back(std::move(v));
    return &views_.back();
}

bool CaptureSlots::Copy(ID3D11DeviceContext* ctx, uint32_t slot, ID3D11Resource* depth, ID3D11Resource* mvec,
                        std::string* error) {
    try {
        if (!ctx) {
            SetError(error, "CaptureSlots: null context");
            return false;
        }
        // Capture runs on CSP's immediate context only (spec 6.5 "Deferred contexts").
        if (ctx->GetType() != D3D11_DEVICE_CONTEXT_IMMEDIATE) {
            SetError(error, "CaptureSlots: not an immediate context");
            return false;
        }
        if (!Valid(slot)) {
            SetError(error, "CaptureSlots: slot index out of range");
            return false;
        }
        if (!Matches(slot, depth, mvec)) {
            SetError(error, "CaptureSlots: the sources do not match slot " + std::to_string(slot) +
                                (HasTextures(slot) ? "" : " (empty)") + "; Recreate it first");
            return false;
        }
        Slot& s = slots_[slot];
        ComPtr<ID3D11Texture2D> depthTex, mvecTex;
        D3D11_TEXTURE2D_DESC dd{}, md{};
        AsTexture2D(depth, &depthTex, &dd);
        AsTexture2D(mvec, &mvecTex, &md);

        ++copies_;
        std::string err;
        SourceView* view = ViewFor(depthTex.Get(), &err);
        if (!view) {
            SetError(error, "CaptureSlots: " + err);
            return false;
        }

        // Motion vectors: subresource 0 into the slot texture of the same typed format.
        ctx->CopySubresourceRegion(s.mvec11.Get(), 0, 0, 0, 0, mvecTex.Get(), 0, nullptr);
        if (view->copy) ctx->CopySubresourceRegion(view->copy.Get(), 0, 0, 0, 0, depthTex.Get(), 0, nullptr);

        // Depth: the blit, with CSP's compute state saved and restored.
        {
            ComputeStateGuard state(ctx);
            ctx->CSSetShader(blit_.Get(), nullptr, 0);
            ID3D11UnorderedAccessView* uav = s.depth_uav.Get();
            ctx->CSSetUnorderedAccessViews(0, 1, &uav, nullptr);
            ID3D11ShaderResourceView* srv = view->srv.Get();
            ctx->CSSetShaderResources(0, 1, &srv);
            std::unique_ptr<DepthStencilUnbind> unbind;
            if (!BoundSrv0Is(ctx, srv)) {
                // The source is bound for output; only the depth-stencil view is handled.
                unbind = std::make_unique<DepthStencilUnbind>(ctx, depthTex.Get());
                if (unbind->Active()) {
                    if (++dsv_unbinds_ == 1)
                        LOGI("capture: the depth source is the bound depth-stencil view; unbinding it for the blit");
                    ctx->CSSetShaderResources(0, 1, &srv);
                }
                if (!BoundSrv0Is(ctx, srv)) {
                    ID3D11ShaderResourceView* none = nullptr;
                    ctx->CSSetShaderResources(0, 1, &none);
                    unbind.reset();
                    SetError(error, "CaptureSlots: the depth source is bound for output and cannot be read");
                    return false;
                }
            }
            ctx->Dispatch((dd.Width + kBlitGroup - 1) / kBlitGroup, (dd.Height + kBlitGroup - 1) / kBlitGroup, 1);
            // Our SRV goes before the depth-stencil view is re-bound; the guard
            // then restores CSP's SRV, UAV and shader.
            ID3D11ShaderResourceView* none = nullptr;
            ctx->CSSetShaderResources(0, 1, &none);
            unbind.reset();
        }
        return true;
    } catch (...) {
        SetError(error, "CaptureSlots: exception in Copy");
        return false;
    }
}

ID3D12Resource* CaptureSlots::Depth12(uint32_t slot) const { return Valid(slot) ? slots_[slot].depth12.Get() : nullptr; }
ID3D12Resource* CaptureSlots::Mvec12(uint32_t slot) const { return Valid(slot) ? slots_[slot].mvec12.Get() : nullptr; }
ID3D11Texture2D* CaptureSlots::Depth11(uint32_t slot) const {
    return Valid(slot) ? slots_[slot].depth11.Get() : nullptr;
}
ID3D11Texture2D* CaptureSlots::Mvec11(uint32_t slot) const { return Valid(slot) ? slots_[slot].mvec11.Get() : nullptr; }
DXGI_FORMAT CaptureSlots::MvecFormat(uint32_t slot) const {
    return Valid(slot) ? slots_[slot].mvec_format : DXGI_FORMAT_UNKNOWN;
}
size_t CaptureSlots::CachedSourceViews() const { return views_.size(); }
uint32_t CaptureSlots::DsvUnbinds() const { return dsv_unbinds_; }

}  // namespace acdb
